server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    url: jdbc:mysql://ec2-34-205-18-229.compute-1.amazonaws.com:3306/ohgiraffers_db?serverTimezone=Asia/Seoul
    username: ohgiraffers
    password: ohgiraffers
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
